apiVersion: v1
kind: Service
metadata:
  name: inventory-api
  namespace: inventory-app
  labels:
    app.kubernetes.io/name: inventory-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: inventory-api
  ports:
    - name: http
      port: 5000
      targetPort: http
