apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: inventory-app

resources:
  - namespace.yaml
  - configmap-backend.yaml
  - configmap-frontend-nginx.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
  - hpa-backend.yaml
  - hpa-frontend.yaml
  # - redis.yaml   # uncomment + set REDIS_URL when scaling API past 1 replica

# After creating k8s/secrets.yaml from secrets.example.yaml:
# resources:
#   - secrets.yaml
