export const ROUTES = {
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  DASHBOARD: '/dashboard',
  JOBS: '/jobs',
  JOB_DETAIL: '/jobs/:id',
  JOB_LABEL: '/jobs/:id/label',
  LABELS: '/labels',
  SCAN: '/scan',
  HISTORY: '/history',
  SUPPLIES: '/supplies',
  PRINT_LABELS: '/print-labels',
  CLIENTS: '/clients',
  LOCATIONS: '/locations',
  USERS: '/users',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  WEATHER_DEMO: '/weather-demo',
}
